/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DevRouteImport } from './routes/_dev'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppCropDoctorRouteImport } from './routes/_app.crop-doctor'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDiseaseIntelligenceRouteImport } from './routes/_app.disease-intelligence'
import { Route as AppFarmsRouteImport } from './routes/_app.farms'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSatelliteMonitoringRouteImport } from './routes/_app.satellite-monitoring'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSoilIntelligenceRouteImport } from './routes/_app.soil-intelligence'
import { Route as AppSprayRecommendationRouteImport } from './routes/_app.spray-recommendation'
import { Route as AuthAccountCreatedRouteImport } from './routes/_auth.account-created'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as DevDeveloperRouteImport } from './routes/_dev.developer'
import { Route as AppDiseaseIntelligenceLibraryRouteImport } from './routes/_app.disease-intelligence.library'
import { Route as AppFarmsCalendarRouteImport } from './routes/_app.farms.calendar'
import { Route as AppFarmsFieldsRouteImport } from './routes/_app.farms.fields'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppProfileAccountRouteImport } from './routes/_app.profile.account'
import { Route as AppProfileActivityRouteImport } from './routes/_app.profile.activity'
import { Route as AppProfileAppearanceRouteImport } from './routes/_app.profile.appearance'
import { Route as AppProfileDevicesRouteImport } from './routes/_app.profile.devices'
import { Route as AppProfileEditRouteImport } from './routes/_app.profile.edit'
import { Route as AppProfileLanguageRouteImport } from './routes/_app.profile.language'
import { Route as AppProfileNotificationsRouteImport } from './routes/_app.profile.notifications'
import { Route as AppProfileSecurityRouteImport } from './routes/_app.profile.security'
import { Route as AppProfileSubscriptionRouteImport } from './routes/_app.profile.subscription'
import { Route as DevDeveloperIndexRouteImport } from './routes/_dev.developer.index'
import { Route as DevDeveloperApiKeysRouteImport } from './routes/_dev.developer.api-keys'
import { Route as DevDeveloperApiProductsRouteImport } from './routes/_dev.developer.api-products'
import { Route as DevDeveloperBillingRouteImport } from './routes/_dev.developer.billing'
import { Route as DevDeveloperDocsRouteImport } from './routes/_dev.developer.docs'
import { Route as DevDeveloperLogsRouteImport } from './routes/_dev.developer.logs'
import { Route as DevDeveloperPlaygroundRouteImport } from './routes/_dev.developer.playground'
import { Route as DevDeveloperSettingsRouteImport } from './routes/_dev.developer.settings'
import { Route as DevDeveloperTeamRouteImport } from './routes/_dev.developer.team'
import { Route as DevDeveloperUsageRouteImport } from './routes/_dev.developer.usage'
import { Route as DevDeveloperWebhooksRouteImport } from './routes/_dev.developer.webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/_dev',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCropDoctorRoute = AppCropDoctorRouteImport.update({
  id: '/crop-doctor',
  path: '/crop-doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDiseaseIntelligenceRoute = AppDiseaseIntelligenceRouteImport.update({
  id: '/disease-intelligence',
  path: '/disease-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSatelliteMonitoringRoute = AppSatelliteMonitoringRouteImport.update({
  id: '/satellite-monitoring',
  path: '/satellite-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSoilIntelligenceRoute = AppSoilIntelligenceRouteImport.update({
  id: '/soil-intelligence',
  path: '/soil-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppSprayRecommendationRoute = AppSprayRecommendationRouteImport.update({
  id: '/spray-recommendation',
  path: '/spray-recommendation',
  getParentRoute: () => AppRoute,
} as any)
const AuthAccountCreatedRoute = AuthAccountCreatedRouteImport.update({
  id: '/account-created',
  path: '/account-created',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DevDeveloperRoute = DevDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DevRoute,
} as any)
const AppDiseaseIntelligenceLibraryRoute =
  AppDiseaseIntelligenceLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AppDiseaseIntelligenceRoute,
  } as any)
const AppFarmsCalendarRoute = AppFarmsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppFarmsRoute,
} as any)
const AppFarmsFieldsRoute = AppFarmsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppFarmsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileAccountRoute = AppProfileAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileActivityRoute = AppProfileActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileAppearanceRoute = AppProfileAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileDevicesRoute = AppProfileDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileLanguageRoute = AppProfileLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileNotificationsRoute = AppProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileSubscriptionRoute = AppProfileSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppProfileRoute,
} as any)
const DevDeveloperIndexRoute = DevDeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperApiKeysRoute = DevDeveloperApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperApiProductsRoute = DevDeveloperApiProductsRouteImport.update({
  id: '/api-products',
  path: '/api-products',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperBillingRoute = DevDeveloperBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperDocsRoute = DevDeveloperDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperLogsRoute = DevDeveloperLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperPlaygroundRoute = DevDeveloperPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperSettingsRoute = DevDeveloperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperTeamRoute = DevDeveloperTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperUsageRoute = DevDeveloperUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DevDeveloperRoute,
} as any)
const DevDeveloperWebhooksRoute = DevDeveloperWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DevDeveloperRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/crop-doctor': typeof AppCropDoctorRoute
  '/dashboard': typeof AppDashboardRoute
  '/disease-intelligence': typeof AppDiseaseIntelligenceRouteWithChildren
  '/farms': typeof AppFarmsRouteWithChildren
  '/help': typeof AppHelpRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/satellite-monitoring': typeof AppSatelliteMonitoringRoute
  '/settings': typeof AppSettingsRoute
  '/soil-intelligence': typeof AppSoilIntelligenceRoute
  '/spray-recommendation': typeof AppSprayRecommendationRoute
  '/account-created': typeof AuthAccountCreatedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/developer': typeof DevDeveloperRouteWithChildren
  '/disease-intelligence/library': typeof AppDiseaseIntelligenceLibraryRoute
  '/farms/calendar': typeof AppFarmsCalendarRoute
  '/farms/fields': typeof AppFarmsFieldsRoute
  '/profile/account': typeof AppProfileAccountRoute
  '/profile/activity': typeof AppProfileActivityRoute
  '/profile/appearance': typeof AppProfileAppearanceRoute
  '/profile/devices': typeof AppProfileDevicesRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/language': typeof AppProfileLanguageRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/subscription': typeof AppProfileSubscriptionRoute
  '/developer/api-keys': typeof DevDeveloperApiKeysRoute
  '/developer/api-products': typeof DevDeveloperApiProductsRoute
  '/developer/billing': typeof DevDeveloperBillingRoute
  '/developer/docs': typeof DevDeveloperDocsRoute
  '/developer/logs': typeof DevDeveloperLogsRoute
  '/developer/playground': typeof DevDeveloperPlaygroundRoute
  '/developer/settings': typeof DevDeveloperSettingsRoute
  '/developer/team': typeof DevDeveloperTeamRoute
  '/developer/usage': typeof DevDeveloperUsageRoute
  '/developer/webhooks': typeof DevDeveloperWebhooksRoute
  '/profile/': typeof AppProfileIndexRoute
  '/developer/': typeof DevDeveloperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AppAdminRoute
  '/crop-doctor': typeof AppCropDoctorRoute
  '/dashboard': typeof AppDashboardRoute
  '/disease-intelligence': typeof AppDiseaseIntelligenceRouteWithChildren
  '/farms': typeof AppFarmsRouteWithChildren
  '/help': typeof AppHelpRoute
  '/notifications': typeof AppNotificationsRoute
  '/satellite-monitoring': typeof AppSatelliteMonitoringRoute
  '/settings': typeof AppSettingsRoute
  '/soil-intelligence': typeof AppSoilIntelligenceRoute
  '/spray-recommendation': typeof AppSprayRecommendationRoute
  '/account-created': typeof AuthAccountCreatedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/disease-intelligence/library': typeof AppDiseaseIntelligenceLibraryRoute
  '/farms/calendar': typeof AppFarmsCalendarRoute
  '/farms/fields': typeof AppFarmsFieldsRoute
  '/profile/account': typeof AppProfileAccountRoute
  '/profile/activity': typeof AppProfileActivityRoute
  '/profile/appearance': typeof AppProfileAppearanceRoute
  '/profile/devices': typeof AppProfileDevicesRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/language': typeof AppProfileLanguageRoute
  '/profile/notifications': typeof AppProfileNotificationsRoute
  '/profile/security': typeof AppProfileSecurityRoute
  '/profile/subscription': typeof AppProfileSubscriptionRoute
  '/developer/api-keys': typeof DevDeveloperApiKeysRoute
  '/developer/api-products': typeof DevDeveloperApiProductsRoute
  '/developer/billing': typeof DevDeveloperBillingRoute
  '/developer/docs': typeof DevDeveloperDocsRoute
  '/developer/logs': typeof DevDeveloperLogsRoute
  '/developer/playground': typeof DevDeveloperPlaygroundRoute
  '/developer/settings': typeof DevDeveloperSettingsRoute
  '/developer/team': typeof DevDeveloperTeamRoute
  '/developer/usage': typeof DevDeveloperUsageRoute
  '/developer/webhooks': typeof DevDeveloperWebhooksRoute
  '/profile': typeof AppProfileIndexRoute
  '/developer': typeof DevDeveloperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dev': typeof DevRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/crop-doctor': typeof AppCropDoctorRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disease-intelligence': typeof AppDiseaseIntelligenceRouteWithChildren
  '/_app/farms': typeof AppFarmsRouteWithChildren
  '/_app/help': typeof AppHelpRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/satellite-monitoring': typeof AppSatelliteMonitoringRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/soil-intelligence': typeof AppSoilIntelligenceRoute
  '/_app/spray-recommendation': typeof AppSprayRecommendationRoute
  '/_auth/account-created': typeof AuthAccountCreatedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dev/developer': typeof DevDeveloperRouteWithChildren
  '/_app/disease-intelligence/library': typeof AppDiseaseIntelligenceLibraryRoute
  '/_app/farms/calendar': typeof AppFarmsCalendarRoute
  '/_app/farms/fields': typeof AppFarmsFieldsRoute
  '/_app/profile/account': typeof AppProfileAccountRoute
  '/_app/profile/activity': typeof AppProfileActivityRoute
  '/_app/profile/appearance': typeof AppProfileAppearanceRoute
  '/_app/profile/devices': typeof AppProfileDevicesRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/profile/language': typeof AppProfileLanguageRoute
  '/_app/profile/notifications': typeof AppProfileNotificationsRoute
  '/_app/profile/security': typeof AppProfileSecurityRoute
  '/_app/profile/subscription': typeof AppProfileSubscriptionRoute
  '/_dev/developer/api-keys': typeof DevDeveloperApiKeysRoute
  '/_dev/developer/api-products': typeof DevDeveloperApiProductsRoute
  '/_dev/developer/billing': typeof DevDeveloperBillingRoute
  '/_dev/developer/docs': typeof DevDeveloperDocsRoute
  '/_dev/developer/logs': typeof DevDeveloperLogsRoute
  '/_dev/developer/playground': typeof DevDeveloperPlaygroundRoute
  '/_dev/developer/settings': typeof DevDeveloperSettingsRoute
  '/_dev/developer/team': typeof DevDeveloperTeamRoute
  '/_dev/developer/usage': typeof DevDeveloperUsageRoute
  '/_dev/developer/webhooks': typeof DevDeveloperWebhooksRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_dev/developer/': typeof DevDeveloperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/crop-doctor'
    | '/dashboard'
    | '/disease-intelligence'
    | '/farms'
    | '/help'
    | '/notifications'
    | '/profile'
    | '/satellite-monitoring'
    | '/settings'
    | '/soil-intelligence'
    | '/spray-recommendation'
    | '/account-created'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/developer'
    | '/disease-intelligence/library'
    | '/farms/calendar'
    | '/farms/fields'
    | '/profile/account'
    | '/profile/activity'
    | '/profile/appearance'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/subscription'
    | '/developer/api-keys'
    | '/developer/api-products'
    | '/developer/billing'
    | '/developer/docs'
    | '/developer/logs'
    | '/developer/playground'
    | '/developer/settings'
    | '/developer/team'
    | '/developer/usage'
    | '/developer/webhooks'
    | '/profile/'
    | '/developer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin'
    | '/crop-doctor'
    | '/dashboard'
    | '/disease-intelligence'
    | '/farms'
    | '/help'
    | '/notifications'
    | '/satellite-monitoring'
    | '/settings'
    | '/soil-intelligence'
    | '/spray-recommendation'
    | '/account-created'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/disease-intelligence/library'
    | '/farms/calendar'
    | '/farms/fields'
    | '/profile/account'
    | '/profile/activity'
    | '/profile/appearance'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/security'
    | '/profile/subscription'
    | '/developer/api-keys'
    | '/developer/api-products'
    | '/developer/billing'
    | '/developer/docs'
    | '/developer/logs'
    | '/developer/playground'
    | '/developer/settings'
    | '/developer/team'
    | '/developer/usage'
    | '/developer/webhooks'
    | '/profile'
    | '/developer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_dev'
    | '/onboarding'
    | '/_app/admin'
    | '/_app/crop-doctor'
    | '/_app/dashboard'
    | '/_app/disease-intelligence'
    | '/_app/farms'
    | '/_app/help'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/satellite-monitoring'
    | '/_app/settings'
    | '/_app/soil-intelligence'
    | '/_app/spray-recommendation'
    | '/_auth/account-created'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_dev/developer'
    | '/_app/disease-intelligence/library'
    | '/_app/farms/calendar'
    | '/_app/farms/fields'
    | '/_app/profile/account'
    | '/_app/profile/activity'
    | '/_app/profile/appearance'
    | '/_app/profile/devices'
    | '/_app/profile/edit'
    | '/_app/profile/language'
    | '/_app/profile/notifications'
    | '/_app/profile/security'
    | '/_app/profile/subscription'
    | '/_dev/developer/api-keys'
    | '/_dev/developer/api-products'
    | '/_dev/developer/billing'
    | '/_dev/developer/docs'
    | '/_dev/developer/logs'
    | '/_dev/developer/playground'
    | '/_dev/developer/settings'
    | '/_dev/developer/team'
    | '/_dev/developer/usage'
    | '/_dev/developer/webhooks'
    | '/_app/profile/'
    | '/_dev/developer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev': {
      id: '/_dev'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crop-doctor': {
      id: '/_app/crop-doctor'
      path: '/crop-doctor'
      fullPath: '/crop-doctor'
      preLoaderRoute: typeof AppCropDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disease-intelligence': {
      id: '/_app/disease-intelligence'
      path: '/disease-intelligence'
      fullPath: '/disease-intelligence'
      preLoaderRoute: typeof AppDiseaseIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/satellite-monitoring': {
      id: '/_app/satellite-monitoring'
      path: '/satellite-monitoring'
      fullPath: '/satellite-monitoring'
      preLoaderRoute: typeof AppSatelliteMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soil-intelligence': {
      id: '/_app/soil-intelligence'
      path: '/soil-intelligence'
      fullPath: '/soil-intelligence'
      preLoaderRoute: typeof AppSoilIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spray-recommendation': {
      id: '/_app/spray-recommendation'
      path: '/spray-recommendation'
      fullPath: '/spray-recommendation'
      preLoaderRoute: typeof AppSprayRecommendationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/account-created': {
      id: '/_auth/account-created'
      path: '/account-created'
      fullPath: '/account-created'
      preLoaderRoute: typeof AuthAccountCreatedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dev/developer': {
      id: '/_dev/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DevDeveloperRouteImport
      parentRoute: typeof DevRoute
    }
    '/_app/disease-intelligence/library': {
      id: '/_app/disease-intelligence/library'
      path: '/library'
      fullPath: '/disease-intelligence/library'
      preLoaderRoute: typeof AppDiseaseIntelligenceLibraryRouteImport
      parentRoute: typeof AppDiseaseIntelligenceRoute
    }
    '/_app/farms/calendar': {
      id: '/_app/farms/calendar'
      path: '/calendar'
      fullPath: '/farms/calendar'
      preLoaderRoute: typeof AppFarmsCalendarRouteImport
      parentRoute: typeof AppFarmsRoute
    }
    '/_app/farms/fields': {
      id: '/_app/farms/fields'
      path: '/fields'
      fullPath: '/farms/fields'
      preLoaderRoute: typeof AppFarmsFieldsRouteImport
      parentRoute: typeof AppFarmsRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/account': {
      id: '/_app/profile/account'
      path: '/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof AppProfileAccountRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/activity': {
      id: '/_app/profile/activity'
      path: '/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof AppProfileActivityRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/appearance': {
      id: '/_app/profile/appearance'
      path: '/appearance'
      fullPath: '/profile/appearance'
      preLoaderRoute: typeof AppProfileAppearanceRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/devices': {
      id: '/_app/profile/devices'
      path: '/devices'
      fullPath: '/profile/devices'
      preLoaderRoute: typeof AppProfileDevicesRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/language': {
      id: '/_app/profile/language'
      path: '/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof AppProfileLanguageRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/notifications': {
      id: '/_app/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof AppProfileNotificationsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/security': {
      id: '/_app/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/subscription': {
      id: '/_app/profile/subscription'
      path: '/subscription'
      fullPath: '/profile/subscription'
      preLoaderRoute: typeof AppProfileSubscriptionRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_dev/developer/': {
      id: '/_dev/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DevDeveloperIndexRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/api-keys': {
      id: '/_dev/developer/api-keys'
      path: '/api-keys'
      fullPath: '/developer/api-keys'
      preLoaderRoute: typeof DevDeveloperApiKeysRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/api-products': {
      id: '/_dev/developer/api-products'
      path: '/api-products'
      fullPath: '/developer/api-products'
      preLoaderRoute: typeof DevDeveloperApiProductsRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/billing': {
      id: '/_dev/developer/billing'
      path: '/billing'
      fullPath: '/developer/billing'
      preLoaderRoute: typeof DevDeveloperBillingRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/docs': {
      id: '/_dev/developer/docs'
      path: '/docs'
      fullPath: '/developer/docs'
      preLoaderRoute: typeof DevDeveloperDocsRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/logs': {
      id: '/_dev/developer/logs'
      path: '/logs'
      fullPath: '/developer/logs'
      preLoaderRoute: typeof DevDeveloperLogsRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/playground': {
      id: '/_dev/developer/playground'
      path: '/playground'
      fullPath: '/developer/playground'
      preLoaderRoute: typeof DevDeveloperPlaygroundRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/settings': {
      id: '/_dev/developer/settings'
      path: '/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof DevDeveloperSettingsRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/team': {
      id: '/_dev/developer/team'
      path: '/team'
      fullPath: '/developer/team'
      preLoaderRoute: typeof DevDeveloperTeamRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/usage': {
      id: '/_dev/developer/usage'
      path: '/usage'
      fullPath: '/developer/usage'
      preLoaderRoute: typeof DevDeveloperUsageRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
    '/_dev/developer/webhooks': {
      id: '/_dev/developer/webhooks'
      path: '/webhooks'
      fullPath: '/developer/webhooks'
      preLoaderRoute: typeof DevDeveloperWebhooksRouteImport
      parentRoute: typeof DevDeveloperRoute
    }
  }
}

interface AppDiseaseIntelligenceRouteChildren {
  AppDiseaseIntelligenceLibraryRoute: typeof AppDiseaseIntelligenceLibraryRoute
}

const AppDiseaseIntelligenceRouteChildren: AppDiseaseIntelligenceRouteChildren =
  {
    AppDiseaseIntelligenceLibraryRoute: AppDiseaseIntelligenceLibraryRoute,
  }

const AppDiseaseIntelligenceRouteWithChildren =
  AppDiseaseIntelligenceRoute._addFileChildren(
    AppDiseaseIntelligenceRouteChildren,
  )

interface AppFarmsRouteChildren {
  AppFarmsCalendarRoute: typeof AppFarmsCalendarRoute
  AppFarmsFieldsRoute: typeof AppFarmsFieldsRoute
}

const AppFarmsRouteChildren: AppFarmsRouteChildren = {
  AppFarmsCalendarRoute: AppFarmsCalendarRoute,
  AppFarmsFieldsRoute: AppFarmsFieldsRoute,
}

const AppFarmsRouteWithChildren = AppFarmsRoute._addFileChildren(
  AppFarmsRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileAccountRoute: typeof AppProfileAccountRoute
  AppProfileActivityRoute: typeof AppProfileActivityRoute
  AppProfileAppearanceRoute: typeof AppProfileAppearanceRoute
  AppProfileDevicesRoute: typeof AppProfileDevicesRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileLanguageRoute: typeof AppProfileLanguageRoute
  AppProfileNotificationsRoute: typeof AppProfileNotificationsRoute
  AppProfileSecurityRoute: typeof AppProfileSecurityRoute
  AppProfileSubscriptionRoute: typeof AppProfileSubscriptionRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileAccountRoute: AppProfileAccountRoute,
  AppProfileActivityRoute: AppProfileActivityRoute,
  AppProfileAppearanceRoute: AppProfileAppearanceRoute,
  AppProfileDevicesRoute: AppProfileDevicesRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileLanguageRoute: AppProfileLanguageRoute,
  AppProfileNotificationsRoute: AppProfileNotificationsRoute,
  AppProfileSecurityRoute: AppProfileSecurityRoute,
  AppProfileSubscriptionRoute: AppProfileSubscriptionRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCropDoctorRoute: typeof AppCropDoctorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiseaseIntelligenceRoute: typeof AppDiseaseIntelligenceRouteWithChildren
  AppFarmsRoute: typeof AppFarmsRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSatelliteMonitoringRoute: typeof AppSatelliteMonitoringRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSoilIntelligenceRoute: typeof AppSoilIntelligenceRoute
  AppSprayRecommendationRoute: typeof AppSprayRecommendationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCropDoctorRoute: AppCropDoctorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiseaseIntelligenceRoute: AppDiseaseIntelligenceRouteWithChildren,
  AppFarmsRoute: AppFarmsRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSatelliteMonitoringRoute: AppSatelliteMonitoringRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSoilIntelligenceRoute: AppSoilIntelligenceRoute,
  AppSprayRecommendationRoute: AppSprayRecommendationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAccountCreatedRoute: typeof AuthAccountCreatedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountCreatedRoute: AuthAccountCreatedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DevDeveloperRouteChildren {
  DevDeveloperApiKeysRoute: typeof DevDeveloperApiKeysRoute
  DevDeveloperApiProductsRoute: typeof DevDeveloperApiProductsRoute
  DevDeveloperBillingRoute: typeof DevDeveloperBillingRoute
  DevDeveloperDocsRoute: typeof DevDeveloperDocsRoute
  DevDeveloperLogsRoute: typeof DevDeveloperLogsRoute
  DevDeveloperPlaygroundRoute: typeof DevDeveloperPlaygroundRoute
  DevDeveloperSettingsRoute: typeof DevDeveloperSettingsRoute
  DevDeveloperTeamRoute: typeof DevDeveloperTeamRoute
  DevDeveloperUsageRoute: typeof DevDeveloperUsageRoute
  DevDeveloperWebhooksRoute: typeof DevDeveloperWebhooksRoute
  DevDeveloperIndexRoute: typeof DevDeveloperIndexRoute
}

const DevDeveloperRouteChildren: DevDeveloperRouteChildren = {
  DevDeveloperApiKeysRoute: DevDeveloperApiKeysRoute,
  DevDeveloperApiProductsRoute: DevDeveloperApiProductsRoute,
  DevDeveloperBillingRoute: DevDeveloperBillingRoute,
  DevDeveloperDocsRoute: DevDeveloperDocsRoute,
  DevDeveloperLogsRoute: DevDeveloperLogsRoute,
  DevDeveloperPlaygroundRoute: DevDeveloperPlaygroundRoute,
  DevDeveloperSettingsRoute: DevDeveloperSettingsRoute,
  DevDeveloperTeamRoute: DevDeveloperTeamRoute,
  DevDeveloperUsageRoute: DevDeveloperUsageRoute,
  DevDeveloperWebhooksRoute: DevDeveloperWebhooksRoute,
  DevDeveloperIndexRoute: DevDeveloperIndexRoute,
}

const DevDeveloperRouteWithChildren = DevDeveloperRoute._addFileChildren(
  DevDeveloperRouteChildren,
)

interface DevRouteChildren {
  DevDeveloperRoute: typeof DevDeveloperRouteWithChildren
}

const DevRouteChildren: DevRouteChildren = {
  DevDeveloperRoute: DevDeveloperRouteWithChildren,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
